name: Build & deploy

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Install Node.js and Restore Cache
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install NPM packages
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          PUBLIC_URL: /${{ github.event.repository.name }}/${{ github.event.release.tag_name }}/

      - name: Run tests
        run: npm run test

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: ./${{ github.event.release.tag_name }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Compress files
        uses: papeloto/action-zip@v1
        with:
          files: build/
          dest: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
