name: Build, deploy and release

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract branch or tag name
        uses: tj-actions/branch-names@v5
        id: extract_branch

      - name: Install Node.js and Restore Cache
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install NPM packages
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          PUBLIC_URL: /${{ github.event.repository.name }}/${{ steps.extract_branch.outputs.current_branch }}/

      - name: Run tests
        run: npm run test

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Extract branch or tag name
        uses: tj-actions/branch-names@v5
        id: extract_branch

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: ./${{ steps.extract_branch.outputs.current_branch }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Extract branch or tag name
        uses: tj-actions/branch-names@v5
        id: extract_branch

      - name: Compress files
        uses: papeloto/action-zip@v1
        with:
          files: build/
          dest: ${{ github.event.repository.name }}-${{ steps.extract_branch.outputs.current_branch }}.zip

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.event.repository.name }}-${{ steps.extract_branch.outputs.current_branch }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
