name: Promote to Staging

on: 
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version tag'
        required: true

env:
  DIST_DIR: build
  DEPLOYMENT_PATH: staging

jobs:
  promote:
    name: Promote to Staging
    uses: martinmoscovich/gh-actions/.github/workflows/promote.yml@main
    with:
      to: staging
      tag: ${{ github.event.inputs.release-version }}
      release_filename: '${{ github.event.repository.name }}-${{ github.event.inputs.release-version }}.zip'
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
