name: Releases workflow

# Run for Main releases when the milestone is closed
# - Checkouts the default branch
# - Builds and tests the project
# - Creates a new release and tag with the compressed artifact using the name of the Milestone
# - Deploys the application to Github Pages
on:
  milestone:
    types: [closed]

jobs:
  build:
    uses: martinmoscovich/gh-actions/.github/workflows/npm-build.yml@main
    with:
      node_version: 14
      dist_dir: build
      source_ref: master

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        uses: martinmoscovich/gh-actions/release@main
        with:
          source_ref: master
          dist_dir: build
          tag: ${{ github.event.milestone.title }}
          body: ${{ github.event.milestone.description }}
          release_filename: ${{ github.event.repository.name }}-${{ github.event.milestone.title }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GH Pages
        uses: martinmoscovich/gh-actions/gh-deploy@main
        with:
          dist_dir: build
          github_token: ${{ secrets.GITHUB_TOKEN }}
          to: releases/${{ github.event.milestone.title }}