name: Releases workflow

on:
  push:
    tags:
      - "v*"

env:
  DIST_DIR: build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: martinmoscovich/gh-actions/npm-build@main
        with:
          node_version: 14
          dist_dir: ${{ env.DIST_DIR }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch or tag name
        uses: tj-actions/branch-names@v5
        id: extract_branch

      - name: Create release
        uses: martinmoscovich/gh-actions/release@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist_dir: ${{ env.DIST_DIR }}
          release_filename: ${{ github.event.repository.name }}-${{ steps.extract_branch.outputs.current_branch }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch or tag name
        uses: tj-actions/branch-names@v5
        id: extract_branch

      - name: Deploy to GH Pages
        uses: martinmoscovich/gh-actions/gh-deploy@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist_dir: ${{ env.DIST_DIR }}
          to: releases/${{ steps.extract_branch.outputs.current_branch }}
