name: Workflow test
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: martinmoscovich/gh-actions/npm-build@master
        with:
          node_version: 14
          dist_dir: "build"
